services:
  postgres:
    image: postgres:latest
    container_name: some-postgres
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - "5432:5432"
    
